services:

  mysql80:
    image: mysql:8.0
    command: [ '--server-id=1', '--log-bin=/var/lib/mysql/mysql-bin.log']
    networks:
      default:
        aliases:
          - mysql80
    environment:
      MYSQL_ROOT_PASSWORD: my_password

  mysql84:
    image: mysql:8.4
    command: [ '--server-id=1', '--log-bin=/var/lib/mysql/mysql-bin.log']
    networks:
      default:
        aliases:
          - mysql84
    environment:
      MYSQL_ROOT_PASSWORD: my_password
